[package]
name = "wifi_drone"
version = "0.0.2"
authors = ["Robert Wettstädt <robert.wett@gmail.com>"]
keywords = ["drone", "wifi", "quadcopter", "robotics", "fpv"]

[dependencies]
log = "^0.3"
env_logger = "^0.4"
glutin = "^0.8"